dist: xenial
language: generic
before_script:
- echo 'starting'
script: tests/test_all.sh
env:
  global:
    secure: j+kAGezbwpKIZwrmzRSViPnHpfLNlQYf8D1h5l50krXRAKm2hp4rGibWUUL34uZQDIaZ7hxLOUagP+Na8+pD4dVum9vv8U5xIJ6vjgjN3+qttJKnsE6TPKQa16jujcba4W85t+tOBZAleSCcoxu9jcENyhX4JeRezfF9K+CXVVOl925utdmVHFeJgaMCJwUmxJehwWidXHSE/jnNFY6zYIxqFIawOrR4SqY6iY1R63Sl2wjUvwhuUEoZjYqqmJWOjUDY9u+bL4kncu7I7bY0Rv4qFF+NCu37du/oxBIN20jOetPfzN+UXYM/BborjgHMVbiEZBAhRM3YRxbahoG3UJPLhxr9hHum3X0o0IiULy+DGuaOKT1VmqB3Hj6FJK41OPAr8choSk2ZUW22rHkHvd5ISW4xN8vY1xaRdAHEqCENxQf0cbsIXlvBUlSKTBw4nS92tc+zaGmwfoQFmyIg/797EMkcXOIfcEI/C7IRLMTuSFsBR3tyKfTlpoHixzqCDqtRKNLnXi7uZAJG78KwJ64yS9Nf9jPCJ6FkX5gDf9hPX+Jr02zRIywKK/sOpVKeKM2Lh2d7MNJ3p8qCZxyy5Wr+0I3Om6Os8LxTdKgr5CDqZrLeV12rLjFHyMI9341nVyVlV5bXTbZCD3vYpdg+EhohAkoes3oqXzea7JctYLA=
